/*
 * AlertControlPanel.java
 *
 * Created on 24 May 2006, 23:36
 */

package datasoul.datashow;

import datasoul.config.ConfigObj;
import datasoul.templates.TemplateComboBox;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  samuelm
 */
public class AlertControlPanel extends javax.swing.JPanel {
    
    private ArrayList<String> history;
    
    private Alert activeAlert;
    
    /** Creates new form AlertControlPanel */
    public AlertControlPanel() {
        initComponents();
        cbMainTemplate.setFilterType(TemplateComboBox.FILTER_ALERT);
        cbMonitorTemplate.setFilterType(TemplateComboBox.FILTER_ALERT);
        history = new ArrayList<String>();
        cbHistory.removeAllItems();
        if (!ConfigObj.getInstance().getMainOutput()){
            cbShowOnMonitor1.setVisible(false);
            cbMonitorTemplate.setVisible(false);
            lblTemplateMonitor.setVisible(false);
            cbShowOnMain1.setSelected(true);
            cbShowOnMain1.setVisible(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlert = new javax.swing.JTextArea();
        cbShowOnMain1 = new javax.swing.JCheckBox();
        cbShowOnMonitor1 = new javax.swing.JCheckBox();
        cbMainTemplate = new datasoul.templates.TemplateComboBox();
        jLabel1 = new javax.swing.JLabel();
        lblTemplateMonitor = new javax.swing.JLabel();
        cbMonitorTemplate = new datasoul.templates.TemplateComboBox();
        jLabel13 = new javax.swing.JLabel();
        spnAlertTime = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        btnShowAlert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbHistory = new javax.swing.JComboBox();
        btnCancel = new javax.swing.JButton();

        jLabel3.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Text"));

        txtAlert.setColumns(20);
        txtAlert.setRows(5);
        jScrollPane1.setViewportView(txtAlert);

        cbShowOnMain1.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Show_on_Main_Output"));
        cbShowOnMain1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cbShowOnMain1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        cbShowOnMonitor1.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Show_on_Monitor_Output"));
        cbShowOnMonitor1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cbShowOnMonitor1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel1.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Template"));

        lblTemplateMonitor.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Template"));

        jLabel13.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Duration"));

        spnAlertTime.setModel(new SpinnerNumberModel(1, 1, 999, 1));

        jLabel14.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("seconds"));

        btnShowAlert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasoul/icons/bell.png")));
        btnShowAlert.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Show_Alert"));
        btnShowAlert.setToolTipText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Show_alert"));
        btnShowAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAlertActionPerformed(evt);
            }
        });

        jLabel4.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Recently_used_texts"));

        cbHistory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHistoryActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasoul/icons/button_cancel.png")));
        btnCancel.setText(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("Cancel"));
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cbHistory, 0, 228, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbMainTemplate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(lblTemplateMonitor)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbMonitorTemplate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .add(cbShowOnMain1)
                    .add(cbShowOnMonitor1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(spnAlertTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel14))
                    .add(layout.createSequentialGroup()
                        .add(btnShowAlert)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbHistory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(cbShowOnMain1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(cbMainTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbShowOnMonitor1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTemplateMonitor)
                    .add(cbMonitorTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel13)
                    .add(spnAlertTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnShowAlert)
                    .add(btnCancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (activeAlert != null){
            activeAlert.interrupt();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHistoryActionPerformed
        int index = cbHistory.getSelectedIndex();
        if (index >= 0 && index < history.size()){
            txtAlert.setText( history.get( index ) );
        }
    }//GEN-LAST:event_cbHistoryActionPerformed

    public void notifyAlertEnd(){
        btnShowAlert.setEnabled(true);
        btnCancel.setEnabled(false);
    }
    
    
    private void btnShowAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAlertActionPerformed
        activeAlert = new Alert(this);
        String text = txtAlert.getText();
        activeAlert.setText( text );
        activeAlert.setMainTemplate( cbMainTemplate.getSelectedItem().toString() );
        activeAlert.setMonitorTemplate( cbMonitorTemplate.getSelectedItem().toString() );
        activeAlert.setShowOnMain( cbShowOnMain1.isSelected() );
        activeAlert.setShowOnMonitor( cbShowOnMonitor1.isSelected() );
        activeAlert.setTime( Integer.parseInt(spnAlertTime.getValue().toString()) * 1000 );
        activeAlert.start();
        
        history.add(0, text);
        if (text.length() > 40){
            cbHistory.insertItemAt(text.substring(0, 40) + "...", 0);
        }else{
            cbHistory.insertItemAt(text, 0);
        }
        if (history.size()==6){
            history.remove(5);
            cbHistory.removeItemAt(5);
        }
        btnShowAlert.setEnabled(false);
        btnCancel.setEnabled(true);
        
    }//GEN-LAST:event_btnShowAlertActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnShowAlert;
    private javax.swing.JComboBox cbHistory;
    private datasoul.templates.TemplateComboBox cbMainTemplate;
    private datasoul.templates.TemplateComboBox cbMonitorTemplate;
    private javax.swing.JCheckBox cbShowOnMain1;
    private javax.swing.JCheckBox cbShowOnMonitor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTemplateMonitor;
    private javax.swing.JSpinner spnAlertTime;
    private javax.swing.JTextArea txtAlert;
    // End of variables declaration//GEN-END:variables

    public class HistoryModel extends DefaultComboBoxModel {
        
    }
    
}
