/*
 * DatashowPanel.java
 *
 * Created on 26 de Dezembro de 2005, 23:03
 */

package datasoul.datashow;

import datasoul.*;
import datasoul.util.*;
import datasoul.datashow.*;
import datasoul.song.*;

/**
 *
 * @author  Administrador
 */
public class DatashowPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form DatashowPanel
     */
    public DatashowPanel() {
        initComponents();
        
        auxiliar.setObjectManager(this);
        serviceList.setObjectManager(this);
        preview.setObjectManager(this);
            
    }

public AuxiliarPanel getAuxiliarPanel(){
    return auxiliar;
}
public LivePanel getLivePanel(){
    return live;
}
public PreviewPanel getPreviewPanel(){
    return preview;
}
public ServiceListPanel getServiceListPanel(){
    return serviceList;
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        serviceList = new datasoul.datashow.ServiceListPanel();
        auxiliar = new datasoul.datashow.AuxiliarPanel();
        tabOperation = new javax.swing.JTabbedPane();
        panelOperation = new javax.swing.JPanel();
        split3 = new javax.swing.JSplitPane();
        preview = new datasoul.datashow.PreviewPanel();
        live = new datasoul.datashow.LivePanel();

        jSplitPane2.setDividerLocation(250);
        jSplitPane3.setDividerLocation(400);
        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 11));
        jTabbedPane1.addTab(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("SERVICE_LIST"), serviceList);

        jSplitPane3.setTopComponent(jTabbedPane1);

        jSplitPane3.setRightComponent(auxiliar);

        jSplitPane2.setLeftComponent(jSplitPane3);

        tabOperation.setFont(new java.awt.Font("Arial", 1, 11));
        panelOperation.setFont(new java.awt.Font("Arial", 1, 11));
        split3.setDividerLocation(300);
        preview.setMinimumSize(new java.awt.Dimension(10, 10));
        split3.setLeftComponent(preview);

        live.setMinimumSize(new java.awt.Dimension(10, 10));
        split3.setRightComponent(live);

        org.jdesktop.layout.GroupLayout panelOperationLayout = new org.jdesktop.layout.GroupLayout(panelOperation);
        panelOperation.setLayout(panelOperationLayout);
        panelOperationLayout.setHorizontalGroup(
            panelOperationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(split3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        panelOperationLayout.setVerticalGroup(
            panelOperationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(split3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        tabOperation.addTab(java.util.ResourceBundle.getBundle("datasoul/internationalize").getString("OPERATION"), panelOperation);

        jSplitPane2.setRightComponent(tabOperation);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datasoul.datashow.AuxiliarPanel auxiliar;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private datasoul.datashow.LivePanel live;
    private javax.swing.JPanel panelOperation;
    private datasoul.datashow.PreviewPanel preview;
    private datasoul.datashow.ServiceListPanel serviceList;
    private javax.swing.JSplitPane split3;
    private javax.swing.JTabbedPane tabOperation;
    // End of variables declaration//GEN-END:variables
    
}
