/*
 * DatashowPanel.java
 *
 * Created on 26 de Dezembro de 2005, 23:03
 */

package datasoul.datashow;

import datasoul.*;
import datasoul.config.ConfigObj;
import datasoul.render.ContentManager;
import datasoul.render.SwingPanelContentRender;
import datasoul.util.*;
import datasoul.datashow.*;
import datasoul.song.*;
import java.awt.Dimension;

/**
 *
 * @author  Administrador
 */
public class DatashowPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form DatashowPanel
     */
    public DatashowPanel() {
        initComponents();
        
        ObjectManager.getInstance().setAuxiliarPanel(auxiliar);
        ObjectManager.getInstance().setServiceListPanel(serviceList);
        ObjectManager.getInstance().setPreviewPanel(preview);
        ObjectManager.getInstance().setLivePanel(live);
            
        initPreview();
    }

    private void initPreview(){
        int width, height;
        try{
            width = Integer.parseInt(ConfigObj.getInstance().getMonitorOutputSizeWidth());
        }catch(Exception e){
            width = 640;
        }
        try{
            height = Integer.parseInt(ConfigObj.getInstance().getMonitorOutputSizeHeight());
        }catch(Exception e){
            height = 480;
        }
        
        SwingPanelContentRender contentRender = new SwingPanelContentRender(previewDisplayPanel1);
        contentRender.initDisplay( width, height, 0, 0 );
        
        ContentManager.getInstance().registerPreviewPanel( contentRender );
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane2 = new javax.swing.JSplitPane();
        split3 = new javax.swing.JSplitPane();
        live = new datasoul.datashow.LivePanel();
        pnlPreview = new javax.swing.JPanel();
        pnlPreviewBox = new javax.swing.JPanel();
        previewDisplayPanel1 = new datasoul.render.SwingDisplayPanel();
        cbPreviewSize = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        preview = new datasoul.datashow.PreviewPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        serviceList = new datasoul.datashow.ServiceListPanel();
        auxiliar = new datasoul.datashow.AuxiliarPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jSplitPane2.setDividerLocation(320);
        split3.setDividerLocation(350);
        live.setMinimumSize(new java.awt.Dimension(10, 10));
        split3.setRightComponent(live);

        previewDisplayPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        previewDisplayPanel1.setPreferredSize(new java.awt.Dimension(160, 120));
        previewDisplayPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                previewDisplayPanel1previewDisplayResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout previewDisplayPanel1Layout = new org.jdesktop.layout.GroupLayout(previewDisplayPanel1);
        previewDisplayPanel1.setLayout(previewDisplayPanel1Layout);
        previewDisplayPanel1Layout.setHorizontalGroup(
            previewDisplayPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 156, Short.MAX_VALUE)
        );
        previewDisplayPanel1Layout.setVerticalGroup(
            previewDisplayPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 116, Short.MAX_VALUE)
        );

        cbPreviewSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Don't show", "Small", "Medium", "Large" }));
        cbPreviewSize.setSelectedIndex(1);
        cbPreviewSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPreviewSizeActionPerformed(evt);
            }
        });

        jLabel10.setText("Preview Size:");

        org.jdesktop.layout.GroupLayout pnlPreviewBoxLayout = new org.jdesktop.layout.GroupLayout(pnlPreviewBox);
        pnlPreviewBox.setLayout(pnlPreviewBoxLayout);
        pnlPreviewBoxLayout.setHorizontalGroup(
            pnlPreviewBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlPreviewBoxLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlPreviewBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(pnlPreviewBoxLayout.createSequentialGroup()
                        .add(jLabel10)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cbPreviewSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(previewDisplayPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        pnlPreviewBoxLayout.setVerticalGroup(
            pnlPreviewBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlPreviewBoxLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlPreviewBoxLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(cbPreviewSize, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(previewDisplayPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        preview.setMinimumSize(new java.awt.Dimension(10, 10));

        org.jdesktop.layout.GroupLayout pnlPreviewLayout = new org.jdesktop.layout.GroupLayout(pnlPreview);
        pnlPreview.setLayout(pnlPreviewLayout);
        pnlPreviewLayout.setHorizontalGroup(
            pnlPreviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlPreviewBox, 0, 349, Short.MAX_VALUE)
            .add(preview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        pnlPreviewLayout.setVerticalGroup(
            pnlPreviewLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlPreviewLayout.createSequentialGroup()
                .add(preview, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlPreviewBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        split3.setTopComponent(pnlPreview);

        jSplitPane2.setRightComponent(split3);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setLeftComponent(serviceList);

        jSplitPane1.setRightComponent(auxiliar);

        jSplitPane2.setLeftComponent(jSplitPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
    }//GEN-LAST:event_formComponentResized

    private void cbPreviewSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPreviewSizeActionPerformed
    
        Dimension d;
        
        switch (cbPreviewSize.getSelectedIndex()){
            
            case 0:
                previewDisplayPanel1.setVisible(false);
                break;
                
            case 1:
                previewDisplayPanel1.setVisible(true);
                d = new Dimension(160, 120);
                previewDisplayPanel1.setSize(d);
                previewDisplayPanel1.setPreferredSize(d);
                previewDisplayPanel1.setMinimumSize(d);
                previewDisplayPanel1.setMaximumSize(d);
                break;
            
            case 2:
                previewDisplayPanel1.setVisible(true);
                d = new Dimension(320, 240);
                previewDisplayPanel1.setSize(d);
                previewDisplayPanel1.setPreferredSize(d);
                previewDisplayPanel1.setMinimumSize(d);
                previewDisplayPanel1.setMaximumSize(d);
                break;

            case 3:
                previewDisplayPanel1.setVisible(true);
                d = new Dimension(480, 360);
                previewDisplayPanel1.setSize(d);
                previewDisplayPanel1.setPreferredSize(d);
                previewDisplayPanel1.setMinimumSize(d);
                previewDisplayPanel1.setMaximumSize(d);
                break;
            
        }
        
        previewDisplayPanel1.revalidate();
        pnlPreviewBox.revalidate();
        pnlPreview.revalidate();
        
        
    }//GEN-LAST:event_cbPreviewSizeActionPerformed

    private void previewDisplayPanel1previewDisplayResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_previewDisplayPanel1previewDisplayResized
        
        Dimension dim= previewDisplayPanel1.getSize();
        int height = dim.height;
        int width = (dim.height/3)*4 ;
        dim.setSize(width,height);
        previewDisplayPanel1.setSize(dim);
        
    }//GEN-LAST:event_previewDisplayPanel1previewDisplayResized
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datasoul.datashow.AuxiliarPanel auxiliar;
    private javax.swing.JComboBox cbPreviewSize;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private datasoul.datashow.LivePanel live;
    private javax.swing.JPanel pnlPreview;
    private javax.swing.JPanel pnlPreviewBox;
    private datasoul.datashow.PreviewPanel preview;
    private datasoul.render.SwingDisplayPanel previewDisplayPanel1;
    private datasoul.datashow.ServiceListPanel serviceList;
    private javax.swing.JSplitPane split3;
    // End of variables declaration//GEN-END:variables
    
}
