/* 
 * Copyright 2005-2008 Samuel Mello & Eduardo Schnell
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; version 2 of the License.
 * 
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 * 
 */

/*
 * SongsPanel.java
 *
 * Created on 13 de Dezembro de 2005, 21:59
 */

package datasoul.song;

import datasoul.config.WindowPropConfig;
import datasoul.util.ObjectManager;

/**
 *
 * @author  Administrador
 */
public class SongsPanel extends javax.swing.JPanel {

    private boolean updateSize;

    /**
     * Creates new form SongsPanel
     */
    public SongsPanel() {
        initComponents();
        
        ObjectManager.getInstance().setServiceListPanel(serviceList);
        ObjectManager.getInstance().setSongViewerPanel(songViewer);
        ObjectManager.getInstance().setSongsSearchPanel(songsSearch);
        
        songsSearch.setSourceView(ObjectManager.VIEW_SONGS);

        WindowPropConfig.getInstance().getSongSplit1(split1);
        WindowPropConfig.getInstance().getSongSplit2(split2);
        updateSize = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split1 = new javax.swing.JSplitPane();
        songViewer = new datasoul.song.SongViewerPanel();
        split2 = new javax.swing.JSplitPane();
        serviceList = new datasoul.datashow.ServiceListPanel();
        songsSearch = new datasoul.song.SongsSearchPanel();

        split1.setBorder(null);
        split1.setDividerLocation(300);
        split1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                split1PropertyChange(evt);
            }
        });

        songViewer.setMinimumSize(new java.awt.Dimension(10, 10));
        split1.setRightComponent(songViewer);

        split2.setBorder(null);
        split2.setDividerLocation(350);
        split2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        split2.setMinimumSize(new java.awt.Dimension(10, 10));
        split2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                split2PropertyChange(evt);
            }
        });
        split2.setBottomComponent(serviceList);
        split2.setLeftComponent(songsSearch);

        split1.setLeftComponent(split2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, split1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(split1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void split1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_split1PropertyChange
        if (updateSize && evt.getPropertyName().equals(javax.swing.JSplitPane.DIVIDER_LOCATION_PROPERTY)){
                WindowPropConfig.getInstance().setSongSplit1(Integer.toString(split1.getDividerLocation()));
        }
    }//GEN-LAST:event_split1PropertyChange

    private void split2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_split2PropertyChange
        if (updateSize && evt.getPropertyName().equals(javax.swing.JSplitPane.DIVIDER_LOCATION_PROPERTY)){
                WindowPropConfig.getInstance().setSongSplit2(Integer.toString(split2.getDividerLocation()));
        }
    }//GEN-LAST:event_split2PropertyChange
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datasoul.datashow.ServiceListPanel serviceList;
    private datasoul.song.SongViewerPanel songViewer;
    private datasoul.song.SongsSearchPanel songsSearch;
    private javax.swing.JSplitPane split1;
    private javax.swing.JSplitPane split2;
    // End of variables declaration//GEN-END:variables
    
}
