/* 
 * Copyright 2005-2008 Samuel Mello & Eduardo Schnell
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; version 2 of the License.
 * 
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 * 
 */

/*
 * SwingDisplayPanel.java
 *
 * Created on March 22, 2006, 11:47 PM
 */

package datasoul.render;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author  root
 */
public class SwingDisplayPanel extends javax.swing.JPanel implements ContentDisplay {
    
    private BufferedImage img0;
    private BufferedImage img1;
    private int activeImage;


    /** Creates new form SwingDisplayPanel */
    public SwingDisplayPanel() {
        initComponents();
    }

    @Override
    public void registerOutputImage0(BufferedImage img) {
        this.img0 = img;
    }
    
    @Override
    public void registerOutputImage1(BufferedImage img) {
        this.img1 = img;
    }

    private BufferedImage getActiveImage(){
        if (activeImage == 0){
            return img0;
        }else{
            return img1;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDoubleBuffered(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint (Graphics g){

        super.paint (g);

        BufferedImage img = getActiveImage();

        if (img != null){
            synchronized(img){
                g.drawImage(img, 0,0, this.getWidth(), this.getHeight(), null);
            }
        }else{
            System.out.println("Is null!");
        }
    }
    
    @Override
    public void flip(int i){
        activeImage = i;
        this.repaint();
    }
    
    
    public void initDisplay(int width, int height){
        this.setSize(width, height);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
