#!/bin/bash 

function showerror(){

#set a default, used if $LANG is not set
MSG="Datasoul needs Java Runtime 6 or newer.\nPlease install Java Runtime 6"

LANG1=$(echo $LANG | awk -F_ '{ print $1 }')
case $LANG1 in
	pt)
		MSG="Datasoul precisa de Java Runtime 6 ou mais recente.\nPor favor instale Java Runtime 6"
	;;
	en)
		MSG="Datasoul needs Java Runtime 6 or newer.\nPlease install Java Runtime 6"
	;;
	de) 
		MSG="Um Datasoul auszuführen, wird Java Runtime 6 oder neuer benötigt.\nBitte installieren Sie Java Runtime 6"
	;;

esac

if [[ -x /usr/bin/zenity ]]
then
	zenity --error --text="$MSG" --title="Datasoul"
else
	echo $MSG
fi
}

# find java
MYJAVA=$(which java)
if [[ "$MYJAVA" == "" ]]
then
	showerror 
	exit 0
fi

JVM_VERS=$($MYJAVA -version 2>&1 | grep "1.[5678]" >/dev/null)
if [[ "$?" != "0" ]]
then
	showerror
	exit 0
fi


DSDIR=$(dirname $0)
java -Xmx512m -cp $DSDIR/swing-layout.jar:$DSDIR/xercesImpl.jar:$DSDIR/xml-apis.jar:$DSDIR/datasoul.jar datasoul.DatasoulMainForm
