/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SongChordEditorPanel.java
 *
 * Created on Mar 27, 2010, 1:02:27 AM
 */

package datasoul.serviceitems.song;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author samuel
 */
public class SongChordEditorPanel extends javax.swing.JPanel {

    /** Creates new form SongChordEditorPanel */
    public SongChordEditorPanel() {
        initComponents();
        textChords.setChords(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabs = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlGridTabs = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textChords = new datasoul.util.HighlightTextArea();
        chordsTransposePanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlTabs.setPreferredSize(new java.awt.Dimension(100, 221));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlGridTabs.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(pnlGridTabs);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabsLayout = new javax.swing.GroupLayout(pnlTabs);
        pnlTabs.setLayout(pnlTabsLayout);
        pnlTabsLayout.setHorizontalGroup(
            pnlTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(pnlTabsLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlTabsLayout.setVerticalGroup(
            pnlTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabsLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
        );

        add(pnlTabs, java.awt.BorderLayout.EAST);

        textChords.setColumns(20);
        textChords.setRows(5);
        textChords.setFont(new java.awt.Font("Courier New", 0, 13));
        jScrollPane3.setViewportView(textChords);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "#", "b" }));

        jButton2.setText("-1");

        jButton3.setText("+1");

        jLabel1.setText("Transpose using");

        javax.swing.GroupLayout chordsTransposePanelLayout = new javax.swing.GroupLayout(chordsTransposePanel);
        chordsTransposePanel.setLayout(chordsTransposePanelLayout);
        chordsTransposePanelLayout.setHorizontalGroup(
            chordsTransposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(chordsTransposePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        chordsTransposePanelLayout.setVerticalGroup(
            chordsTransposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(chordsTransposePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chordsTransposePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(chordsTransposePanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateTabs(pnlGridTabs, textChords.getText());
}//GEN-LAST:event_jButton1ActionPerformed


    public void init(){
        textChords.setCaretPosition(0);
    }

    public void setText(String s){
        textChords.setText(s);
    }

    public String getText(){
        return textChords.getText();
    }

    public void setTransposeVisible(boolean b){
        chordsTransposePanel.setVisible(b);
    }

    public void setTabsVisible(boolean b){
        pnlTabs.setVisible(b);
    }

    private void updateTabs(JPanel gridPanel, String songChords){

        /* clean up */
        gridPanel.removeAll();

        /* get used chords */
        ArrayList<String> usedChords = Song.getUsedChords(songChords);

        /* Process it */
        ChordsDB chordsDB = ChordsDB.getInstance();
        for(String chordStr : usedChords){
            Chord chord = chordsDB.getChordByName(chordStr);
            if(chord!=null){
                ChordShapePanel csp = new ChordShapePanel(2, chord.getName(),chord.getShape());
                gridPanel.add(csp);
            }
        }
        gridPanel.revalidate();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chordsTransposePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlGridTabs;
    private javax.swing.JPanel pnlTabs;
    private datasoul.util.HighlightTextArea textChords;
    // End of variables declaration//GEN-END:variables

}
