/* 
 * Copyright 2005-2008 Samuel Mello & Eduardo Schnell
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; version 2 of the License.
 * 
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 * 
 */

/*
 * Splash.java
 *
 * Created on 10 November 2006, 23:01
 */

package datasoul.util;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author  samuelm
 */
public class Splash extends javax.swing.JFrame {
    
    /** Creates new form Splash */
    public Splash() {
//        initComponents();
        init();
        center();
        
    }

    private void init() {
    this.setLayout(null);
        
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("datasoul/internationalize"); // NOI18N
        setTitle(bundle.getString("Starting_Datasoul")); // NOI18N
        setResizable(false);
        setUndecorated(true);
        lblStatus.setText("init");
        getContentPane().add(lblStatus);
        
        ImageIcon image = new ImageIcon(getClass().getResource("/datasoul/icons/splashScreen.gif"));
        jLabel1.setIcon(image);
        jLabel1.setSize(image.getIconWidth(), image.getIconHeight());
        getContentPane().add(jLabel1);

        this.setBounds(0,0,image.getIconWidth()+1, image.getIconHeight()+21);
        
        jLabel1.setLocation(0,0);
        lblStatus.setSize(image.getIconWidth()-20,20);
        lblStatus.setLocation(11,image.getIconHeight());
       
        getContentPane().setBackground(new Color(220,220,220));
        lblStatus.setForeground(Color.BLACK);  

    }// </editor-fold>                        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("datasoul/internationalize"); // NOI18N
        setTitle(bundle.getString("Starting_Datasoul")); // NOI18N
        setResizable(false);
        setUndecorated(true);
        lblStatus.setText("jLabel1");
        getContentPane().add(lblStatus, java.awt.BorderLayout.SOUTH);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datasoul/icons/splashScreen.gif")));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables

    public void setStatusText(String status){
        lblStatus.setText(status);
        setTitle(status);
    }
 
    public void center(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Rectangle frame = getBounds();
        setLocation((screen.width - frame.width)/2, (screen.height - frame.height)/2);
    }
    
    public void paint(Graphics g) {
        super.paint(g);
        
        g.drawRect(0,0,this.getWidth()-1, this.getHeight()-1);        
    }
    
}
